import hmac
import hashlib
import time

start = time.time()
message = input("Enter Message:")
print("Message sent is:",message)
length=len(message)
key= input("Enter key with sender:")

hmac1 = hmac.new(key=key.encode(), msg=message.encode(), digestmod=hashlib.sha256)
message_digest1 = hmac1.digest()

print("Message Digest Generated by sender:\n{}".format(message_digest1))
#verification part
res=message+str(message_digest1)

rec=res
print("\n")
message_rec=rec[:length]
print("Message Received is:",message_rec)
key_r= input("Enter key with receiver:")
hmac2 = hmac.new(key=key_r.encode(), msg=message_rec.encode(), digestmod=hashlib.sha256)
message_digest2 = hmac2.digest()
print("Message Digest generated by receiver: \n{}".format(message_digest2))
print("\n")
if(message_digest2==message_digest1):
       print("\t\t\t\t\t\'Authentication Succesfull.\'")
       file_out=open("message_digest.txt","w")
       file_out.write(res)
       file_out.close()
else:
       print("\t\t\t\t\t\'Authentication Unsuccesfull.\'")

end = time.time()
print("Execution time:",end - start,"seconds")

